### ISSUE TITLE
Doesn't highlight selected word

### ISSUE THREAD

**Issue by alexeiboronnikov** [matt-curtis/Sketch-Highlighter#1]
It only highlights the entire line for some reason. I'm on 39.1 (31720)

**Super useful plugin tho. Thanks a lot!**

**Comment by matt-curtis** [comment]
You're right, thanks! Just pushed out a version that should fix this. Can you try it out and let me know?

**Comment by alexeiboronnikov** [comment]
It works brilliant now! Thanks!
